### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by ghost** [publicus/bookscan#1]
I'm on Ubuntu 16.04 Mate I get errors when trying to compile program:
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o main.o -c -O2 -Wall -I/usr/include/opencv2 -I/usr/include/opencv main.cpp
g++ -o marker.o -c -O2 -Wall -I/usr/include/opencv2 -I/usr/include/opencv marker.cpp
g++ -o page.o -c -O2 -Wall -I/usr/include/opencv2 -I/usr/include/opencv page.cpp
g++ -o build/extpage -L/usr/local/lib -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_calib3d main.o marker.o page.o
main.o: In function `process_image(_IplImage*, std::map<int, CvPoint2D32f, std::less<int>, std::allocator<std::pair<int const, CvPoint2D32f> > >&, LayoutInfo, std::map<int, CvPoint2D32f, std::less<int>, std::allocator<std::pair<int const, CvPoint2D32f> > >&, LayoutInfo)':
main.cpp:(.text+0x4e): undefined reference to`cvShowImage'
main.cpp:(.text+0x58): undefined reference to `cvReleaseImage'
main.cpp:(.text+0x84): undefined reference to`cvShowImage'
main.cpp:(.text+0x8e): undefined reference to `cvReleaseImage'
main.o: In function`main':
main.cpp:(.text.startup+0x263): undefined reference to `cvLoadImage'
main.cpp:(.text.startup+0x2b0): undefined reference to`cvSaveImage'
main.cpp:(.text.startup+0x2bc): undefined reference to `cvReleaseImage'
main.cpp:(.text.startup+0x2ea): undefined reference to`cvSaveImage'
main.cpp:(.text.startup+0x2f6): undefined reference to `cvReleaseImage'
main.cpp:(.text.startup+0x302): undefined reference to`cvReleaseImage'
main.cpp:(.text.startup+0x357): undefined reference to `cvNamedWindow'
main.cpp:(.text.startup+0x36b): undefined reference to`cvResizeWindow'
main.cpp:(.text.startup+0x38a): undefined reference to `cvCreateCameraCapture'
main.cpp:(.text.startup+0x3ab): undefined reference to`cvSetCaptureProperty'
main.cpp:(.text.startup+0x3c0): undefined reference to `cvSetCaptureProperty'
main.cpp:(.text.startup+0x3d4): undefined reference to`cvQueryFrame'
main.cpp:(.text.startup+0x3e4): undefined reference to `cvShowImage'
main.cpp:(.text.startup+0x441): undefined reference to`cvWaitKey'
marker.o: In function `analyze_marker(_IplImage const*, CvSeq*, CvPoint2D32f*)':
marker.cpp:(.text+0x897): undefined reference to`cvCheckContourConvexity'
marker.cpp:(.text+0x8af): undefined reference to `cvContourArea'
marker.cpp:(.text+0x963): undefined reference to`cvFindCornerSubPix'
marker.cpp:(.text+0xa4c): undefined reference to `cvCreateImage'
marker.cpp:(.text+0xb1a): undefined reference to`cvCreateMat'
marker.cpp:(.text+0xb41): undefined reference to `cvFindHomography'
marker.cpp:(.text+0xb90): undefined reference to`cvWarpPerspective'
marker.cpp:(.text+0xbad): undefined reference to `cvCreateImage'
marker.cpp:(.text+0xbc4): undefined reference to`cvResize'
marker.cpp:(.text+0xbd8): undefined reference to `cvAvg'
marker.cpp:(.text+0xc0a): undefined reference to`cvThreshold'
marker.cpp:(.text+0xc5e): undefined reference to `cvSetReal2D'
marker.cpp:(.text+0xc84): undefined reference to`cvCreateMat'
marker.cpp:(.text+0xcef): undefined reference to `cvGetReal2D'
marker.cpp:(.text+0xdfa): undefined reference to`cvResize'
marker.cpp:(.text+0xe09): undefined reference to `cvShowImage'
marker.cpp:(.text+0xe13): undefined reference to`cvReleaseMat'
marker.cpp:(.text+0xe1d): undefined reference to `cvReleaseMat'
marker.cpp:(.text+0xe27): undefined reference to`cvReleaseImage'
marker.cpp:(.text+0xe31): undefined reference to `cvReleaseImage'
marker.cpp:(.text+0xe40): undefined reference to`cvGetSeqElem'
page.o: In function `BookImage::create_page_image(std::map<int, CvPoint2D32f, std::less<int>, std::allocator<std::pair<int const, CvPoint2D32f> > > const&, CvSize)':
page.cpp:(.text+0x42): undefined reference to`cvCreateMat'
page.cpp:(.text+0x65): undefined reference to `cvCreateMat'
page.cpp:(.text+0x208): undefined reference to`cvCreateImage'
page.cpp:(.text+0x21f): undefined reference to `cvCreateMat'
page.cpp:(.text+0x243): undefined reference to`cvFindHomography'
page.cpp:(.text+0x285): undefined reference to `cvWarpPerspective'
page.cpp:(.text+0x293): undefined reference to`cvReleaseMat'
page.cpp:(.text+0x29d): undefined reference to `cvReleaseMat'
page.cpp:(.text+0x2a7): undefined reference to`cvReleaseMat'
page.cpp:(.text+0x346): undefined reference to `cvReleaseMat'
page.cpp:(.text+0x350): undefined reference to`cvReleaseMat'
page.o: In function `BookImage::~BookImage()':
page.cpp:(.text+0x3da): undefined reference to`cvReleaseImage'
page.o: In function `BookImage::BookImage(_IplImage const*)':
page.cpp:(.text+0x4df): undefined reference to`cvCloneImage'
page.cpp:(.text+0x50b): undefined reference to `cvGetSize'
page.cpp:(.text+0x51d): undefined reference to`cvCreateImage'
page.cpp:(.text+0x531): undefined reference to `cvCvtColor'
page.cpp:(.text+0x539): undefined reference to`cvGetSize'
page.cpp:(.text+0x54b): undefined reference to `cvCreateImage'
page.cpp:(.text+0x578): undefined reference to`cvAdaptiveThreshold'
page.cpp:(.text+0x57f): undefined reference to `cvCreateMemStorage'
page.cpp:(.text+0x5aa): undefined reference to`cvFindContours'
page.cpp:(.text+0x5f2): undefined reference to `cvApproxPoly'
page.cpp:(.text+0x603): undefined reference to`cvCheckContourConvexity'
page.cpp:(.text+0x68d): undefined reference to `cvReleaseMemStorage'
page.cpp:(.text+0x696): undefined reference to`cvReleaseImage'
page.cpp:(.text+0x69f): undefined reference to `cvReleaseImage'
collect2: error: ld returned 1 exit status
scons: **\* [build/extpage] Error 1
scons: building terminated because of errors.

and default scons settings not exist on my system so I changed them like this:
`env.AppendUnique(CCFLAGS = ['-I/usr/include/opencv2'])
env.AppendUnique(CCFLAGS = ['-I/usr/include/opencv'])
env.AppendUnique(CCFLAGS = ['-I/usr/include/opencv2'])

env.AppendUnique(LINKFLAGS = ['-L/usr/local/lib'])`

Accutally we need a nice one executable program works with drag folder and program will create an out folder filled with seperated images left and right.

**Comment by jglev** [comment]
Thank you for your report! I'm very slowly working on this (I'm not a C++ developer), and would appreciate any Pull Requests you'd be willing to make!

**Comment by jglev** [comment]
Hello again. I've just added instructions to the Readme for compiling with cmake instead of scons. Thus, I'm closing this issue, as I think it's fixed in spirit (even if the scons compilation issue was never itself solved).

Please do let me know if you encounter any issues with the updated Readme instructions!
